version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build -t $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker login --username=$DOCKER_USER --password=$DOCKER_PASS
      - docker push $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION