version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build -t $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $IMAGE_REPO_NAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION